config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post "zipcode" => 'home#zipcode'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	require 'net/http'
  	require 'json'

  	@url = 'https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=27513&distance=0&API_KEY=3B1F89A0-E4CC-480E-A9A2-79EFB07AAA91'
  	@uri = URI(@url)
  	@response = Net::HTTP.get(@uri)
  	@output = JSON.parse(@response)

	# Check for empty return result
  	if @output.empty?
  		@final_output = "Error"
  	elsif !@output
  		@final_output = "Error"
  	else
  		@final_output = @output[0]['AQI']
  	end

  	if @final_output == "Error"
  		@api_color = "gray"
  	elsif @final_output <= 50
  		@api_color = "green"
  		@api_description = "Good (0 - 50) Air quality is considered satisfactory, and air pollution poses little or no risk."
  	elsif @final_output >= 51 && @final_output <= 100
  		@api_color = "yellow"
  		@api_description = "Moderate (51 - 100) Air quality is acceptable; however, for some pollutants there may be a moderate health concern for a very small number of people who are unusually sensitive to air pollution."
  	elsif @final_output >= 101 && @final_output <= 150
  		@api_color = "orange"
  		@api_description = "Unhealthy for Sensitive Groups (101 - 150)
Although general public is not likely to be affected at this AQI range, people with lung disease, older adults and children are at a greater risk from exposure to ozone, whereas persons with heart and lung disease, older adults and children are at greater risk from the presence of particles in the air."
  	elsif @final_output >= 151 && @final_output <= 200
  		@api_color = "red"
  		@api_description = "Unhealthy (151 - 200)
Everyone may begin to experience health effects; members of sensitive groups may experience more serious health effects."
  	elsif @final_output >= 201 && @final_output <= 300
  		@api_color = "purple"
  		@api_description = "Very Unhealthy (201 - 300)
Health alert: everyone may experience more serious health effects."
  	elsif @final_output >= 301 && @final_output <= 500
  		@api_color = "maroon"
  		@api_description = "Hazardous (301 - 500)
Health warnings of emergency conditions. The entire population is more likely to be affected."
  	end
  end

  def zipcode
  	@zip_query = params[:zipcode]

  	if params[:zipcode] == ""
      @final_output = "Error"
      @api_color = "gray"
    elsif params[:zipcode]
      # Do Api stuff

      require 'net/http'
      require 'json'

      @url = 'http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=' + @zip_query + '&distance=0&API_KEY=96A38DFD-5C56-4740-AD99-E38C0C855A1B'
      @uri = URI(@url)
      @response = Net::HTTP.get(@uri)
      @output = JSON.parse(@response)

    # Check for empty return result
      if @output.empty?
        @final_output = "Error"
      elsif !@output
        @final_output = "Error"
      else
        @final_output = @output[0]['AQI']
      end

      if @final_output == "Error"
        @api_color = "gray"
      elsif @final_output <= 50
        @api_color = "green"
        @api_description = "Good (0 - 50) Air quality is considered satisfactory, and air pollution poses little or no risk."
      elsif @final_output >= 51 && @final_output <= 100
        @api_color = "yellow"
        @api_description = "Moderate (51 - 100) Air quality is acceptable; however, for some pollutants there may be a moderate health concern for a very small number of people who are unusually sensitive to air pollution."
      elsif @final_output >= 101 && @final_output <= 150
        @api_color = "orange"
        @api_description = "Unhealthy for Sensitive Groups (101 - 150)
  Although general public is not likely to be affected at this AQI range, people with lung disease, older adults and children are at a greater risk from exposure to ozone, whereas persons with heart and lung disease, older adults and children are at greater risk from the presence of particles in the air."
      elsif @final_output >= 151 && @final_output <= 200
        @api_color = "red"
        @api_description = "Unhealthy (151 - 200)
  Everyone may begin to experience health effects; members of sensitive groups may experience more serious health effects."
      elsif @final_output >= 201 && @final_output <= 300
        @api_color = "purple"
        @api_description = "Very Unhealthy (201 - 300)
  Health alert: everyone may experience more serious health effects."
      elsif @final_output >= 301 && @final_output <= 500
        @api_color = "maroon"
        @api_description = "Hazardous (301 - 500)
  Health warnings of emergency conditions. The entire population is more likely to be affected."
      end
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <%= link_to "My Ozone", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
    </ul>
    <%= form_tag zipcode_path, :method => 'POST' do %>
    <div class="form-inline my-2 my-lg-0">
      <%= text_field_tag 'zipcode', nil, placeholder: "Search Zipcode", class: "form-control mr-sm-2" %>
      <%= submit_tag 'Search', class: 'btn btn-outline-secondary my-2 my-sm-0' %>
      </div>
    <% end %>
  </div>
</nav>

app/views/home/index.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4"><%= @final_output %></h1>
  <p class="lead">This is the current ozone air quality readout for my neighborhood in Raleigh.</p>
  <hr class="my-4">
  <p><%= @api_description %></p>
  <br/>
</div>
<br/>

app/views/home/zipcode.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4"><%= @final_output %></h1>
  <p class="lead">This is the current ozone air quality readout for the <%= @zip_query %> zipcode.</p>
  <hr class="my-4">
  <p><%= @api_description %></p>
  <br/>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ozone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
      <br/>
      <%= yield %>
    </div>
  </body>
</html>